queue_rules: []
pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
    actions:
      merge:
merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 10"
  - name: Only merge with validation label
    description: Make sure PR has a validation label
    if:
      - base = main
    success_conditions:
      - or:
          - label = Validation needed
          - label = Validation done
