<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>tripleo.elijah</groupId>
	<artifactId>congenial-robot</artifactId>
	<packaging>pom</packaging>
	<version>congenial.2024-04</version>

	<!-- TODO 12/31 naming here -->
	<name>eljc-almost-congenial-robot</name>
	<url>http://git.sr.ht/~tripleo/el-almost</url>

	<properties>
		<project.build.outputTimestamp>1</project.build.outputTimestamp>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>

		<downloadSources>true</downloadSources>

		<jacoco.version>0.8.9</jacoco.version>

		<!-- for edu 2022.2 -->
		<!--		<kotlin.version>1.7.10</kotlin.version>-->
		<kotlin.version>1.9.21</kotlin.version>
	</properties>

	<modules>
		<module>elijah-congenial-core</module>
		<module>elijah-congenial-core.test</module>
	</modules>

	<dependencies>
		<dependency>
			<groupId>com.github.elijah-team</groupId>
			<artifactId>congenial-upper</artifactId>
			<version>3fe9f9565622c759429a7e9ae8a4ed30195b30cf</version>
		</dependency>

		<!--
		<dependency>
			<groupId>com.github.elijah-team.lombok</groupId>
			<artifactId>lombok</artifactId>
			<version>master-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		-->

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>

		<!-- https://search.maven.org/artifact/fr.inria.gforge.spoon.labs/gumtree-spoon-ast-diff/1.69/jar-->
		<!--
    <dependency>
        <groupId>fr.inria.gforge.spoon.labs</groupId>
        <artifactId>gumtree-spoon-ast-diff</artifactId>
        <version>1.69</version>
    </dependency>
    -->

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.19.0</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.0.17</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.0.17</version>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>5.20.0</version>
			<scope>test</scope>
		</dependency>

		<!--
		<dependency>
			<groupId>com.github.spotbugs</groupId>
			<artifactId>spotbugs-annotations</artifactId>
			<version>4.7.3</version>
		</dependency>
		-->

		<dependency>
			<groupId>com.github.JCTools.JCTools</groupId>
			<artifactId>jctools-core</artifactId>
			<version>v4.0.5</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<build>
		<pluginManagement>
			<plugins>
				<!--
								<plugin>
									<groupId>org.eclipse.sisu</groupId>
									<artifactId>sisu-maven-plugin</artifactId>
									<version>0.3.5</version>
									<executions>
										<execution>
											<id>generate-index</id>
											<goals>
												<goal>main-index</goal>
												<goal>test-index</goal>
											</goals>
										</execution>
									</executions>
								</plugin>
				-->
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>2.20.1</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>33.5.0-jre</version>
			</dependency>
			<dependency>
				<groupId>com.google.code.gson</groupId>
				<artifactId>gson</artifactId>
				<version>2.13.2</version>
			</dependency>
			<dependency>
				<groupId>org.jetbrains</groupId>
				<artifactId>annotations</artifactId>
				<version>26.0.2-1</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
