<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>tripleo.elijah</groupId>
		<artifactId>congenial-robot</artifactId>
		<version>congenial.2024-04</version>
	</parent>

	<artifactId>tripleo.elijah.congenial.core</artifactId>
	<name>Elijah Congenial CORE</name>
	<description>Main impl for elijah-congenial-core</description>
	<properties>
		<kotlin.version>2.1.20</kotlin.version>
		<maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
		<auto-service.version>1.1.1</auto-service.version>
	</properties>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.42</version>
			<scope>provided</scope>
		</dependency>

		<!-- https://search.maven.org/artifact/io.reactivex.rxjava3/rxjava/3.1.0/jar -->
		<dependency>
			<groupId>io.reactivex.rxjava3</groupId>
			<artifactId>rxjava</artifactId>
			<version>3.1.12</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.reactivestreams/reactive-streams -->
		<dependency>
			<groupId>org.reactivestreams</groupId>
			<artifactId>reactive-streams</artifactId>
			<version>1.0.4</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.19.0</version> 				<!-- Use 1.6 for java 1.5 -->
		</dependency>

		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>26.0.2-1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib-jdk8</artifactId>
			<version>${kotlin.version}</version>
		</dependency>

		<dependency>
			<groupId>org.checkerframework</groupId>
			<artifactId>checker-qual</artifactId>
			<version>3.52.0</version>
			<scope>provided</scope>
		</dependency>
<!--
		<dependency>
			<groupId>com.google.auto.service</groupId>
			<artifactId>auto-service</artifactId>
			<version>${auto-service.version}</version>
			<scope>provided</scope>
		</dependency>
--> 
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.6.1</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>./src-damar/elijah-sourcemodel-api/src/main/java</source>
								<source>./src-damar/elijah-sourcemodel-impl/src/main/java</source>
								<source>./src-damar/elijah-good-api/src/main/java</source>
								<source>./src-bnxn/elijah-nextgen-outputstatement/src/main/java</source>
								<source>./src-bnxn/elijah-stateful/src/main/java</source>
								<source>./src-bnxn/tripleo-small/src/main/java</source>
								<source>./src-bnxn/tripleo-reactive/src/main/java</source>
								
								<source>./src-bnxn/tripleo-buffers/src/main/java</source>
								<source>./src-bnxn/tripleo-range/src/main/java</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-plugin</artifactId>
				<version>${kotlin.version}</version>
				<executions>
					<execution>
						<id>compile</id>
						<phase>process-sources</phase>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<sourceDirs>
								<sourceDir>target/generated-sources/annotations</sourceDir>
								<sourceDir>target/generated-sources/kapt</sourceDir>
								<sourceDir>target/generated-sources/kaptKotlin</sourceDir>
							</sourceDirs>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<jvmTarget>1.8</jvmTarget>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>none</phase>
					</execution>
					<execution>
						<id>compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
			</plugins>
	</build>
</project>