name: Elijah Congenial with Maven 3.9.9

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # !!
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Surefire with Maven
        run: mvn -B --file pom.xml test

      - name: Package with Maven
        run: mvn -B --file pom.xml package

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
##      - name: Update dependency graph
##        uses: advanced-security/maven-dependency-submission-action@df268dd1684fb95352aa463056e3cf41f9acb94b
